# Generated by Django 5.2 on 2025-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
