# Generated by Django 5.2 on 2025-04-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist_is_public_playlist_user_song_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_covers/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_playlists', to='music.playlist'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
    ]
