# Generated by Django 5.2 on 2025-04-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playlist_cover_image_playlist_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='year',
        ),
    ]
